# Generated by Django 4.1.5 on 2023-05-28 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(blank=True, max_length=255, null=True, verbose_name='Город')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='URL')),
                ('image', models.ImageField(upload_to='tours/', verbose_name='Фото')),
            ],
            options={
                'verbose_name': 'Город',
                'verbose_name_plural': 'Города',
            },
        ),
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Имя')),
                ('last_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Фамилия')),
                ('surname', models.CharField(max_length=255, verbose_name='Отчество')),
                ('b_day', models.DateField(blank=True, null=True, verbose_name='Дата рождения')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Адрес')),
                ('phone', models.CharField(blank=True, max_length=11, null=True, verbose_name='Телефон')),
            ],
            options={
                'verbose_name': 'Клиента',
                'verbose_name_plural': 'Клиенты',
            },
        ),
        migrations.CreateModel(
            name='Countries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(blank=True, max_length=255, null=True, verbose_name='Страна')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='URL')),
                ('image', models.ImageField(upload_to='tours/', verbose_name='Фото')),
            ],
            options={
                'verbose_name': 'Страну',
                'verbose_name_plural': 'Страны',
            },
        ),
        migrations.CreateModel(
            name='Flights',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight_number', models.CharField(blank=True, max_length=255, null=True, verbose_name='Номер рейса')),
                ('city_departure', models.CharField(blank=True, max_length=255, null=True, verbose_name='Город вылета')),
                ('date_departure', models.DateField(blank=True, null=True, verbose_name='Дата вылета')),
                ('time_departure', models.CharField(blank=True, max_length=20, null=True, verbose_name='Время вылета')),
                ('city_arrival', models.CharField(blank=True, max_length=255, null=True, verbose_name='Город прилета')),
                ('date_arrival', models.DateField(blank=True, null=True, verbose_name='Дата прилета')),
                ('time_arrival', models.CharField(blank=True, max_length=20, null=True, verbose_name='Время Прилета')),
            ],
            options={
                'verbose_name': 'Рейс',
                'verbose_name_plural': 'Рейсы',
            },
        ),
        migrations.CreateModel(
            name='FoodType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_type', models.CharField(blank=True, max_length=255, null=True, verbose_name='Тип питания')),
            ],
            options={
                'verbose_name': 'Тип питания',
                'verbose_name_plural': 'Типы питания',
            },
        ),
        migrations.CreateModel(
            name='Hotels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('stars', models.CharField(choices=[(1, '*'), (2, '* *'), (3, '* * *'), (4, '* * * *'), (5, '* * * * *')], max_length=1, verbose_name='Звезды')),
                ('description', models.CharField(max_length=255, verbose_name='Описание')),
                ('image', models.ImageField(null=True, upload_to='tours/', verbose_name='Фото')),
                ('image1', models.ImageField(null=True, upload_to='tours/', verbose_name='Фото')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tours.cities', verbose_name='Город')),
            ],
            options={
                'verbose_name': 'Отель',
                'verbose_name_plural': 'Отели',
            },
        ),
        migrations.CreateModel(
            name='TourType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tour_type', models.CharField(blank=True, max_length=255, null=True, verbose_name='Тип тура')),
            ],
            options={
                'verbose_name': 'Тип тура',
                'verbose_name_plural': 'Типы туров',
            },
        ),
        migrations.CreateModel(
            name='TypeAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_allocation', models.CharField(blank=True, max_length=255, null=True, verbose_name='Тип размещения')),
            ],
            options={
                'verbose_name': 'Тип размещения',
                'verbose_name_plural': 'Типы размещения',
            },
        ),
        migrations.CreateModel(
            name='Tours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='URL')),
                ('description', models.CharField(max_length=255, verbose_name='Описание')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Дата начала')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Дата конца')),
                ('price', models.CharField(blank=True, max_length=20, null=True, verbose_name='Цена')),
                ('arrival', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tours.flights', verbose_name='Прилет')),
                ('departure', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dep', to='tours.flights', verbose_name='Вылет')),
                ('food_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tours.foodtype', verbose_name='Тип питания')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tours.hotels', verbose_name='Отель')),
                ('tour_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tours.tourtype', verbose_name='Тип тура')),
            ],
            options={
                'verbose_name': 'Тур',
                'verbose_name_plural': 'Туры',
            },
        ),
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Дата')),
                ('price', models.CharField(blank=True, max_length=15, null=True, verbose_name='Цена')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tours.clients', verbose_name='Клиент')),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tours.tours', verbose_name='Тур')),
            ],
            options={
                'verbose_name': 'Продажу',
                'verbose_name_plural': 'Продажи',
            },
        ),
        migrations.AddField(
            model_name='hotels',
            name='type_allocation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tours.typeallocation', verbose_name='Тип размещения'),
        ),
        migrations.AddField(
            model_name='cities',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tours.countries', verbose_name='Страна'),
        ),
    ]
