# Generated by Django 4.1.5 on 2023-05-28 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotels',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='hotels',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='tours/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='hotels',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='tours/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='hotels',
            name='stars',
            field=models.CharField(choices=[('1', '*'), ('2', '* *'), ('3', '* * *'), ('4', '* * * *'), ('5', '* * * * *')], max_length=10, verbose_name='Звезды'),
        ),
    ]
