# Generated by Django 4.1.5 on 2023-05-30 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0002_alter_hotels_description_alter_hotels_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourtype',
            name='slug',
            field=models.SlugField(default='tour', max_length=200, verbose_name='URL'),
        ),
    ]
