# Generated by Django 4.1.5 on 2023-06-06 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0004_alter_tourtype_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cities',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='country_in_city', to='tours.countries', verbose_name='Страна'),
        ),
    ]
