# Generated by Django 4.1.5 on 2023-07-07 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0008_remove_sales_client_remove_sales_tour_delete_clients_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='body',
            field=models.TextField(verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='name',
            field=models.CharField(max_length=80, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='tours',
            name='arrival',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='arri', to='tours.flights', verbose_name='Прилет'),
        ),
    ]
